# This program allows a user guess the random words generated by the computer
import random

file = open("twist.txt", 'r')

for words in file:

    words = words.split(' ')

#random_choice = list(random.choice(words))
random_choice = ['d','o','o']

intro = input("please press enter to begin : ")
question = input("i have word can you guess it? y,n : ")
length = len(random_choice)
guess_trial = 0
no_of_trials = length+ 10
correct_guess = 0
random_choice_copy = random_choice.copy()
print(random_choice)

if question == 'y':

    guess_spaces  = list(("_" * len(random_choice)))

    while guess_trial <= no_of_trials:

        print(' '.join(guess_spaces))
        #guess_letter = input("Take a guess")
        guess_trial += 1

        if  guess_spaces != random_choice:
            guess_letter = input("Take a guess")
            print(guess_spaces, random_choice)
            if guess_letter in random_choice:

                correct_guess += 1
                index_space = random_choice_copy.index(guess_letter) 
                random_choice_copy[index_space] = '_'
                guess_spaces[index_space] =  guess_letter
        
            elif guess_letter not in random_choice:

                if guess_trial > 5 and correct_guess <= 1:

                    clue = random.choice(random_choice)
                    index_space = random_choice.index(clue) 
                    guess_spaces[index_space] = clue

        else:
            break
    if guess_trial < length + 2:
        print(f'you are great at guessing, you guessed the word in {guess_trial} trials')
    print (f"your number of correct guess is/are {correct_guess} out of {length} letter words and {guess_trial} trials")
            
     
        
        
 

# items = ['d','d','a']
# items1 = ['-','-','-']
# #item = input('entr a letter : ')
# # for index, letter in enumerate(items):
# #     index1 = items.index(item)
# #     items1[index1] = item

# # print(items1)
# i = 0
# # while i < 3:
# #     i+=1
# #     item = input('entr a letter : ')
# #     for item in items:
# #         index1 = items.index(item)
# #         print(item,index1)
# #         items1[index1] = item
        

            


# print(set(items))
# #rint(items[1])

# while i < 3:
#     i += 1
#     item = input('entr a letter : ')
#     if item in items:
#         index1 = items.index(item)
#         items1[index1] = item
#     if item in items > 1 == True:


# print(items1)
